source :rubygems

gem 'slim' # ever put slim before espresso
gem 'appetite', git: 'git://github.com/slivu/appetite.git'
gem 'e', git: 'git://github.com/slivu/espresso.git'
gem 'reel', git: 'git://github.com/celluloid/reel.git'
gem 'specular'
gem 'sonar'
gem 'json'
gem 'oauth2'
gem 'rest-client'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'posix-spawn'
gem 'bluepill'
